apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kd4dt-vol
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10000Gi
